[package]
name = "unifii"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "normalizer"

[dependencies]
shared = {path = "../shared"}
uniffi = "0.8"
uniffi_macros = "0.8"

[build-dependencies]
uniffi_build = "0.8"
